Test failure

diff --git a/gating/pre_merge_test/run b/gating/pre_merge_test/run
--- a/gating/pre_merge_test/run
+++ b/gating/pre_merge_test/run
@@ -27,6 +27,8 @@ export RE_HOOK_RESULT_DIR="${RE_HOOK_RESULT_DIR:-/tmp/results}"
 
 ## Main ----------------------------------------------------------------------
 
+echo "Test failure."
+exit 1
 if [[ $RE_JOB_ACTION == "tox-test" ]]; then
   bash -c "$(readlink -f $(dirname ${0})/run_tox.sh)"
 elif [[ $RE_JOB_IMAGE =~ .*mnaio.* ]]; then
